[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "18" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ws", "lightningcss"]

# Diese Umleitung ist nicht notwendig und verursacht Fehler
# Netlify leitet automatisch zu Funktionen unter /.netlify/functions/ weiter

# API-Anfragen zur Netlify-Funktion umleiten
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA-Routing - alle nicht gefundenen Seiten zur index.html umleiten
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200