[build]
  command = "./build-netlify.sh"
  publish = "dist"
  functions = "netlify/functions"

# Umleitung für API-Anfragen zu den Netlify-Funktionen
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# API-Anfragen zur Netlify-Funktion umleiten
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA-Routing - alle nicht gefundenen Seiten zur index.html umleiten
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200